
#+TITLE: PHIL 220
#+AUTHOR: Andrew Hooke
#+OPTIONS: tex:t num:nil
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
* Menu
  #+begin_export html
  <p><a href="https://zjquid.github.io/">Homepage</a></p>
  #+end_export
* Jan 11 2022
** What reasons might there be for thinking that there is or isn't a God as traditionally concieved and what difference would this make?
- Knowledge of "large" events like weather - where in the past these things were attributed to acts of God - can now be explained. A drought, for example, might be seen as punishment from God in the past, and in the present day, can be accurately pinned on a number of things (but not the moral standing of the people).
- This difference puts a certain amount of blame on different sources, one former the people themselves, and the latter being on environmental factors.
- Gives purpose to people's lives.
- Human exceptionalism, humans being more important that other creatures due to the idea of being created in God's image. 
** The Course
*** The Basics
- Primarily philosophical, not historical.
- Philosophical --> human reason. "Natural Theology" as opposed to "Real Theology."  
- Arguments in favor of and against conceptions of God - Classical Theism
  * Judaism, Christianity, Islam
- Why focus on this?
  * Classical Theism has shaped western society, and is most prevalent in our lives.
*** The Goals
- Learn some major arguments in central problems of the philosophy of religion.
- To improve the ability to critically and actively read major work in the philosophy of religion.
- To grow in the ability to make philosophical arguments and pose philosophical questions, both verbally and in writing.
- To become more proficient in productively engaging viewpoints quite different from your own.
  * Professor's goal is to be a moderator, not use this course as a soapbox to project his own beliefs/opinions on said viewpoints.

** 1.1 - Some Logic
*** Deductive arguments
- Validity is only about the structure of the argument, not about the truth of the premises or conclusion
- Soundness of argument - an argument is sound if it is valid and the premises are true
- Example:
  * if mars is the size of a marble, then I am Kanye West.
  * mars is the size of a marble.
  * therefore, I am Kanye West.
  This argument is valid, but not sound (because the premises are not true).
  Validity is about *structure*.
**** Logical Fallacies
- Affirming the consequent
  Basically running the argument backwards, not necessarily valid.
- Denying the antecedent
  Basically the opposite/negative version of the argument: if NOT this, then NOT that... not necessarily valid.  

* Jan 13 2022
** William Rowe
- The Cosmological Argument
  * Every being is either a dependent being, or a self-existent being
  * Not every being can be a dependent being
  * Therefore, there exists a self-existent being
This argument is *deductibly valid* - if the premises are true, then the conclusion is always true.    

- Structure of the argument:
  * Either A or B
  * Not A...
  * Therefore B!
This is a *disjunctive syllogism*

** The Principle of Sufficient Reason
- Premise 1 seems trivial, but Rowe claims it isn't
- Premise 1 denies the idea that things exist by nothing, with no explanation:
- The PSR:
  * There must be an explanation of (a) the existence of any being, and (b) of any positive fact whatsoever.
  * If the first part of the PSR is true, then the first premise is true.
** The Second Premise
- Suppose A_1 is the only being that exists, gives birth to A_2, etc. towards A_n
- It seems like every being is a dependent being
- Implementing temporal ideas to prove premise 2:
  * There must be a *temporally first* being to start any causal series
  * If every being were dependent there would be no temporally first being to start the causal series
  * Therefore, not every being can be a dependent being
- In the world where A_1 gives birth to A_2, then A_1 dies, in the lonely world of just A_2, PSRa is true, but PSRb is not - there is no explanation of the existence of A_2 itself.
** Objections
- Not all being can be dependent beings:
  * Treating a series of dependent beings is treated as if the series itself were a dependent being - the *series* as a concept is dependent on something.
- The cosmological argument claims that if each individual member of the series has a cause, the series as a whole has a cause. This is fallacious: it like inferring the entire human race has a mother because each individual has a mother.
- just look at the 1.2 handout
** Responses to objections
- 1: A collection of human beings is not a human beings - there exists a concept of a collection
- 2: just look at the 1.2 handout

** Question:
*** What are the best reasons for thinking the PSR holds all the time? What are the best reasons for thinking that it doesn't?
- Does:
  * The reason for existence can be explained by the existence itself - like the A_n series example.
  * Just because we can't find a reason doesn't mean a reason doesn't exist - we might just not have the ability to find one.
  * Our inability to explain is an explanation in itself.    
- Doesn't:
  * This seems like a cop-out, saying that everything has a reason, and if we can't find one, it exists but we have no capability to find/understand it... but at the same time there is no reason not to believe this "cop-out" answer.
  * Using this idea, we may not have the capability to find an explanation why the PSR doesn't hold up.
This is confusing.    
