#+TITLE: PHIL 220
#+AUTHOR: Andrew Hooke
#+OPTIONS: tex:t num:nil
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
* Menu
  #+begin_export html
  <p><a href="https://zjquid.github.io/">Homepage</a></p>
  #+end_export
* Jan 11 2022
** What reasons might there be for thinking that there is or isn't a God as traditionally concieved and what difference would this make?
- Knowledge of "large" events like weather - where in the past these things were attributed to acts of God - can now be explained. A drought, for example, might be seen as punishment from God in the past, and in the present day, can be accurately pinned on a number of things (but not the moral standing of the people).
- This difference puts a certain amount of blame on different sources, one former the people themselves, and the latter being on environmental factors.
- Gives purpose to people's lives.
- Human exceptionalism, humans being more important that other creatures due to the idea of being created in God's image. 
** The Course
*** The Basics
- Primarily philosophical, not historical.
- Philosophical --> human reason. "Natural Theology" as opposed to "Real Theology."  
- Arguments in favor of and against conceptions of God - Classical Theism
  * Judaism, Christianity, Islam
- Why focus on this?
  * Classical Theism has shaped western society, and is most prevalent in our lives.
*** The Goals
- Learn some major arguments in central problems of the philosophy of religion.
- To improve the ability to critically and actively read major work in the philosophy of religion.
- To grow in the ability to make philosophical arguments and pose philosophical questions, both verbally and in writing.
- To become more proficient in productively engaging viewpoints quite different from your own.
  * Professor's goal is to be a moderator, not use this course as a soapbox to project his own beliefs/opinions on said viewpoints.



** 1.1 - Some Logic
*** Deductive arguments
- Validity is only about the structure of the argument, not about the truth of the premises or conclusion
- Soundness of argument - an argument is sound if it is valid and the premises are true
- Example:
  * if mars is the size of a marble, then I am Kanye West.
  * mars is the size of a marble.
  * therefore, I am Kanye West.
  This argument is valid, but not sound (because the premises are not true).
  Validity is about *structure*.
**** Logical Fallacies
- Affirming the consequent
  Basically running the argument backwards, not necessarily valid.
- Denying the antecedent
  Basically the opposite/negative version of the argument: if NOT this, then NOT that... not necessarily valid.  
